version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.87.1"
    
phases:
  install:
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/hugo_extended_0.87.0_Linux-64bit.tar.gz
      - tar -xzf hugo_extended_0.87.0_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd 
      - rm -rf /tmp
  build:
    commands:
      - cd ~/environment/quickstart
      - rm -rf public
      - hugo deploy
  post_build:
    commands:
      #- aws s3 sync --delete public s3://dukefeb1
      - echo Build completed on `date`